### ISSUE TITLE
Really looking forward to this!

### ISSUE THREAD

**Issue by load1n9** [djfos/dimgui#2]
when you get distribution working like [build-glfw](https://github.com/deno-windowing/build-glfw) would really like to make an official imgui extension for dwm as such if its ok with you [https://github.com/deno-windowing/dwm/blob/imgui-extension/examples/imgui.ts](https://github.com/deno-windowing/dwm/blob/imgui-extension/examples/imgui.ts)

**Comment by djfos** [comment]
Oh, I don't even know that there is a imgui-extension branch in that repo! Do you mean that we should embed the shared library into strings in the ts file? I agree with that, and it seems the only way to distribute binary in Deno, currently.

**Comment by djfos** [comment]
@load1n9 How about this? #3 BTW, the temp dll file created per a version number (like what dwm does), but it's content may change during development (like adding some helper functions in c file). I don't think pump version number is a good way in development. Maybe we need hash the file? Any idea?

**Comment by load1n9** [comment]
maybe do what dwm does for glfw and host it by version number on deno deploy
