### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by nhrones** [djfos/dimgui#7]
What is the status of this project?

Percent complete?

Roadmap?

Anyway I could help? I was rolling my own GUI with Skia-Canvas.  This project will kill that.

**Comment by djfos** [comment]
Sorry for the late reply. I have no time to spend on this project anymore, at least in this year. I started this project when I was trying to write a render engine in Typescript. I found there were so many things missing in the ecosystem, and the Ui framework is one of them. I won't archive this project. Just leave it here. I would be glad if any part of this repo is helpful. BTW, what do you mean by "This project will kill that"?

**Comment by nhrones** [comment]
I meant that if this worked as described, I would have no reason to continue building my own renderer from scratch.  I have a framework that used DWM and skia-canvas to manually render UI widgets.  I have all the basic widgets, button, checkbox, text-input, and a multiline text editor.  That was a lot of work that I would gladly toss out if there was a viable stable alternative (not DOM based).  
My DWM-GUI framework is a retained-mode GUI that is very efficient - only renders what is `dirty`; it's based on an MVVM-reactive architecture where Widgets render from code-behind Viewmodels. 
Anyway, I'm just an old man playing around.  Will probably lose interest soon.
Thanks for your response.
